# Generated by Django 4.0.4 on 2022-05-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(choices=[('c', 'c'), ('c++', 'c++'), ('python', 'python')], max_length=30)),
                ('author', models.CharField(choices=[('dennis ritchie', 'dennis ritchie'), ('bjourne stratustrup', 'bjourne stratustrup'), ('guido van rosuum', 'guido van rosuum')], max_length=20)),
                ('bookcount', models.IntegerField()),
                ('recvdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdid', models.IntegerField(primary_key=True, serialize=False)),
                ('stdname', models.CharField(max_length=30)),
                ('course', models.CharField(choices=[('java', 'java'), ('python', 'python'), ('php', 'php')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('issid', models.IntegerField(primary_key=True, serialize=False)),
                ('issdate', models.DateField()),
                ('bookcount', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
