# Generated by Django 4.0.4 on 2022-05-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issued',
            old_name='book',
            new_name='bookid',
        ),
    ]
